'use client'

import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle2, Clock3, Headphones, MessageSquareText, Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog,DialogBody,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger } from '@/components/ui/dialog'

type Ticket={id:string;club_id:string|null;universe_id:string|null;category:string;priority:string;status:string;subject:string;description:string;created_at:string;updated_at:string}
type Note={id:string;ticket_id:string;author_user_id:string|null;internal:boolean;body:string;created_at:string}
type Club={id:string;name:string;universe_id:string}
const categories=['PAYMENT','ECONOMY','MATCH','MARKET','ACCOUNT','UNIVERSE','MODERATION','TECHNICAL','OTHER']

export function SupportClient({userId,tickets,notes,clubs}:{userId:string;tickets:Ticket[];notes:Note[];clubs:Club[]}){
  const router=useRouter();const[createOpen,setCreateOpen]=useState(false);const[selected,setSelected]=useState<Ticket|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null)
  const[category,setCategory]=useState('TECHNICAL');const[subject,setSubject]=useState('');const[description,setDescription]=useState('');const[clubId,setClubId]=useState('');const[reply,setReply]=useState('')
  const openCount=tickets.filter(t=>!['RESOLVED','CLOSED'].includes(t.status)).length,waiting=tickets.filter(t=>t.status==='WAITING_USER').length,resolved=tickets.filter(t=>['RESOLVED','CLOSED'].includes(t.status)).length
  const notesByTicket=useMemo(()=>{const map=new Map<string,Note[]>();for(const note of notes)map.set(note.ticket_id,[...(map.get(note.ticket_id)??[]),note]);return map},[notes])
  async function call(payload:Record<string,unknown>){setLoading(true);setError(null);try{const response=await fetch('/api/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'support_operation_failed');router.refresh();return true}catch(e){setError(e instanceof Error?e.message:'support_operation_failed');return false}finally{setLoading(false)}}
  async function createTicket(event:React.FormEvent){event.preventDefault();const club=clubs.find(item=>item.id===clubId);const ok=await call({action:'create',category,subject,description,clubId:club?.id??null,universeId:club?.universe_id??null});if(ok){setCreateOpen(false);setSubject('');setDescription('');setClubId('')}}
  async function sendReply(event:React.FormEvent){event.preventDefault();if(!selected)return;const ok=await call({action:selected.status==='CLOSED'?'reopen':'reply',ticketId:selected.id,body:reply});if(ok){setSelected(null);setReply('')}}
  return <div className="mx-auto max-w-6xl space-y-7">
    <section className="brand-watermark rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Headphones className="h-5 w-5 text-primary"/><p className="clan-kicker">Suporte</p></div><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Centro de suporte</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Abre pedidos, acompanha o estado e responde à equipa sem sair da plataforma. Notas internas nunca são expostas aqui.</p></div><Dialog open={createOpen} onOpenChange={value=>{if(!loading){setCreateOpen(value);setError(null)}}}><DialogTrigger asChild><Button><Plus className="h-4 w-4"/>Novo pedido</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo pedido de suporte</DialogTitle><DialogDescription>Escolhe o contexto certo para acelerar a triagem.</DialogDescription></DialogHeader><DialogBody><form id="support-create" onSubmit={createTicket} className="space-y-4"><Field label="Categoria"><select value={category} onChange={e=>setCategory(e.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm">{categories.map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Clube relacionado (opcional)"><select value={clubId} onChange={e=>setClubId(e.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"><option value="">Sem clube específico</option>{clubs.map(club=><option key={club.id} value={club.id}>{club.name}</option>)}</select></Field><Field label="Assunto"><input required minLength={4} maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3.5 text-sm outline-none focus:border-primary/45"/></Field><Field label="Descrição"><textarea required minLength={10} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)} rows={6} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm outline-none focus:border-primary/45"/></Field>{error&&<ErrorText>{error}</ErrorText>}</form></DialogBody><DialogFooter><Button type="button" variant="ghost" onClick={()=>setCreateOpen(false)} disabled={loading}>Cancelar</Button><Button type="submit" form="support-create" disabled={loading}>{loading?'A enviar…':'Criar pedido'}</Button></DialogFooter></DialogContent></Dialog></div></section>
    <section className="grid gap-3 sm:grid-cols-3"><Metric icon={Clock3} label="Em acompanhamento" value={openCount}/><Metric icon={MessageSquareText} label="Aguardam a tua resposta" value={waiting}/><Metric icon={CheckCircle2} label="Resolvidos / fechados" value={resolved}/></section>
    <section className="space-y-4">{tickets.length===0?<div className="rounded-2xl border border-dashed border-white/[.08] bg-black/15 px-6 py-14 text-center"><Headphones className="mx-auto h-7 w-7 text-primary/50"/><p className="mt-3 font-bold">Ainda não tens pedidos.</p><p className="mt-1 text-sm text-muted-foreground">Cria um pedido quando precisares de ajuda da equipa.</p></div>:tickets.map(ticket=>{const ticketNotes=notesByTicket.get(ticket.id)??[];return <article key={ticket.id} className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Status value={ticket.status}/><span className="text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{ticket.category} · {ticket.priority}</span></div><h2 className="mt-3 text-lg font-black">{ticket.subject}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{ticket.description}</p></div><p className="text-[10px] text-muted-foreground">Atualizado {new Date(ticket.updated_at).toLocaleString('pt-PT')}</p></div>{ticketNotes.length>0&&<div className="mt-5 space-y-2 border-t border-white/[.06] pt-4">{ticketNotes.map(note=><div key={note.id} className={`rounded-xl border p-3 ${note.author_user_id===userId?'border-primary/10 bg-primary/[.025]':'border-white/[.06] bg-black/20'}`}><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-bold uppercase tracking-[.11em] text-muted-foreground">{note.author_user_id===userId?'Tu':'Equipa de suporte'}</p><span className="text-[9px] text-muted-foreground">{new Date(note.created_at).toLocaleString('pt-PT')}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{note.body}</p></div>)}</div>}<div className="mt-4 flex justify-end"><Button size="sm" variant="outline" onClick={()=>{setSelected(ticket);setReply('');setError(null)}}>{ticket.status==='CLOSED'?'Reabrir pedido':ticket.status==='RESOLVED'?'Responder e reabrir':'Responder'}</Button></div></article>})}</section>
    <Dialog open={Boolean(selected)} onOpenChange={value=>{if(!value&&!loading)setSelected(null)}}><DialogContent><DialogHeader><DialogTitle>{selected?.status==='CLOSED'?'Reabrir pedido':'Responder ao suporte'}</DialogTitle><DialogDescription>{selected?.subject}</DialogDescription></DialogHeader><DialogBody><form id="support-reply" onSubmit={sendReply}><Field label={selected?.status==='CLOSED'?'Motivo para reabrir':'Mensagem'}><textarea required minLength={2} maxLength={4000} value={reply} onChange={e=>setReply(e.target.value)} rows={6} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm outline-none focus:border-primary/45"/></Field>{error&&<ErrorText>{error}</ErrorText>}</form></DialogBody><DialogFooter><Button type="button" variant="ghost" onClick={()=>setSelected(null)} disabled={loading}>Cancelar</Button><Button type="submit" form="support-reply" disabled={loading||reply.trim().length<2}>{loading?'A enviar…':selected?.status==='CLOSED'?'Reabrir':'Enviar resposta'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-bold text-muted-foreground">{label}</span>{children}</label>}
function Metric({icon:Icon,label,value}:{icon:typeof Clock3;label:string;value:number}){return <div className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5"><Icon className="h-4 w-4 text-primary"/><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>}
function Status({value}:{value:string}){return <span className={`rounded-md border px-2 py-1 text-[9px] font-black uppercase tracking-[.12em] ${value==='WAITING_USER'?'border-primary/20 bg-primary/[.06] text-primary':['RESOLVED','CLOSED'].includes(value)?'border-white/[.07] bg-white/[.03] text-muted-foreground':'border-emerald-500/15 bg-emerald-500/[.05] text-emerald-300'}`}>{value.replaceAll('_',' ')}</span>}
function ErrorText({children}:{children:React.ReactNode}){return <p className="mt-3 rounded-xl border border-destructive/20 bg-destructive/[.06] p-3 text-xs text-destructive">{children}</p>}
