'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {Scale} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {ConfirmationDialog} from '@/components/ui/confirmation-dialog'
import type {ClubLiability} from '@/lib/domain/operations'
export function LiabilityOperationsClient({liabilities,silverBalance}:{liabilities:ClubLiability[];silverBalance:number}){const router=useRouter();const[pending,setPending]=useState<ClubLiability|null>(null);const[amount,setAmount]=useState(0);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const open=liabilities.filter(l=>['OPEN','PARTIALLY_PAID'].includes(l.state));function begin(l:ClubLiability){setPending(l);setAmount(Math.min(l.outstandingAmount,silverBalance));setError(null)}async function pay(){if(!pending||amount<=0)return;setLoading(true);setError(null);try{const r=await fetch('/api/economy/liability/pay',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({liabilityId:pending.id,amount,idempotencyKey:crypto.randomUUID()})});const p=await r.json();if(!r.ok)throw new Error(p.error||'liability_payment_failed');setPending(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:'liability_payment_failed')}finally{setLoading(false)}}if(open.length===0)return null;return <section className="rounded-2xl border border-destructive/12 bg-[#0b0b0b] p-5 sm:p-6"><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-destructive"/><h2 className="text-xl font-black">Obrigações em aberto</h2></div><p className="mt-2 text-xs text-muted-foreground">Custos que não puderam ser integralmente liquidados no ciclo financeiro.</p><div className="mt-5 space-y-3">{open.map(l=><article key={l.id} className="flex flex-col gap-3 rounded-xl border border-white/[.06] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{l.liabilityType}</p><p className="mt-1 text-xs text-muted-foreground">Em dívida: {l.outstandingAmount.toLocaleString('pt-PT')} S · {l.state}</p></div><Button size="sm" variant="outline" disabled={silverBalance<=0} onClick={()=>begin(l)}>Amortizar</Button></article>)}</div><ConfirmationDialog open={Boolean(pending)} onOpenChange={o=>{if(!o&&!loading)setPending(null)}} title="Amortizar liability" description="O pagamento debita Silver do clube e reduz a obrigação de forma auditável." confirmLabel="Pagar" isLoading={loading} onConfirm={pay}>{pending&&<><label className="text-xs font-bold text-muted-foreground">Valor a pagar</label><Input className="mt-2" type="number" min={1} max={Math.min(pending.outstandingAmount,silverBalance)} value={amount} onChange={e=>setAmount(Math.floor(Number(e.target.value)))}/><div className="mt-3 space-y-2 rounded-xl border border-white/[.06] p-3 text-sm"><R l="Saldo atual" v={`${silverBalance.toLocaleString('pt-PT')} S`}/><R l="Em dívida" v={`${pending.outstandingAmount.toLocaleString('pt-PT')} S`}/><R l="Saldo após" v={`${Math.max(0,silverBalance-amount).toLocaleString('pt-PT')} S`}/></div></>}{error&&<p className="mt-2 text-xs text-destructive">{error}</p>}</ConfirmationDialog></section>}
function R({l,v}:{l:string;v:string}){return <div className="flex justify-between gap-4"><span className="text-muted-foreground">{l}</span><span className="font-black tabular-nums">{v}</span></div>}
