'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {Handshake} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {ConfirmationDialog} from '@/components/ui/confirmation-dialog'
import type {SponsorshipContract} from '@/lib/domain/club-economy'
export function SponsorshipOperationsClient({contracts}:{contracts:SponsorshipContract[]}){const router=useRouter();const[pending,setPending]=useState<SponsorshipContract|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const offered=contracts.filter(c=>c.state==='OFFERED');const active=contracts.filter(c=>c.state==='ACTIVE');async function accept(){if(!pending)return;setLoading(true);setError(null);try{const r=await fetch('/api/economy/sponsorship/accept',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contractId:pending.id,idempotencyKey:crypto.randomUUID()})});const p=await r.json();if(!r.ok)throw new Error(p.error||'sponsorship_accept_failed');setPending(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:'sponsorship_accept_failed')}finally{setLoading(false)}}return <section className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><div className="flex items-center gap-2"><Handshake className="h-5 w-5 text-primary"/><h2 className="text-xl font-black">Patrocínios</h2></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{active.map(c=><Card key={c.id} c={c} active/>)}{offered.map(c=><Card key={c.id} c={c} action={<Button size="sm" onClick={()=>{setError(null);setPending(c)}}>Aceitar oferta</Button>}/>) }{active.length===0&&offered.length===0&&<p className="col-span-full py-8 text-center text-sm text-muted-foreground">Ainda não existe uma oferta comercial. O worker económico gera ofertas para clubes elegíveis.</p>}</div><ConfirmationDialog open={Boolean(pending)} onOpenChange={o=>{if(!o&&!loading)setPending(null)}} title="Aceitar patrocínio" description="O signing bonus entra imediatamente em Silver pelo ledger. O pagamento periódico entra nos ciclos financeiros seguintes." confirmLabel="Assinar contrato" isLoading={loading} onConfirm={accept}>{pending&&<div className="space-y-2 rounded-xl border border-white/[.06] p-3 text-sm"><R l="Signing bonus" v={`${pending.signingBonus.toLocaleString('pt-PT')} S`}/><R l="Pagamento por ciclo" v={`${pending.periodicPayment.toLocaleString('pt-PT')} S`}/><R l="Bónus objetivo" v={`${pending.objectiveBonus.toLocaleString('pt-PT')} S`}/></div>}{error&&<p className="mt-2 text-xs text-destructive">{error}</p>}</ConfirmationDialog></section>}
function Card({c,active=false,action}:{c:SponsorshipContract;active?:boolean;action?:React.ReactNode}){return <article className={`rounded-xl border p-4 ${active?'border-primary/15 bg-primary/[.025]':'border-white/[.06]'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-black">{c.name}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{c.state}</p></div>{action}</div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><R l="Assinatura" v={`${c.signingBonus.toLocaleString('pt-PT')} S`}/><R l="Periódico" v={`${c.periodicPayment.toLocaleString('pt-PT')} S`}/></div></article>}
function R({l,v}:{l:string;v:string}){return <div><p className="text-[9px] uppercase tracking-[.12em] text-muted-foreground">{l}</p><p className="mt-1 font-black tabular-nums">{v}</p></div>}
