import Link from 'next/link'
import { Bell, Clock3, Newspaper, RefreshCw, ShoppingCart, Trophy } from 'lucide-react'
import type { JournalArticle, Notification } from '@/lib/domain/communications'

interface RecentActivityProps { articles:JournalArticle[]; notifications:Notification[] }
type Item={id:string;kind:'ARTICLE'|'NOTIFICATION';title:string;summary:string;date:string;category:string;href:string|null;unread:boolean}

export function RecentActivity({articles,notifications}:RecentActivityProps){
  const items:Item[]=[
    ...articles.map(a=>({id:`a:${a.id}`,kind:'ARTICLE' as const,title:a.title,summary:a.summary,date:a.publishedAt,category:a.category,href:null,unread:false})),
    ...notifications.map(n=>({id:`n:${n.id}`,kind:'NOTIFICATION' as const,title:n.title,summary:n.body,date:n.createdAt,category:n.type,href:n.href,unread:!n.readAt})),
  ].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).slice(0,7)
  return <section className="clan-panel-neutral overflow-hidden rounded-2xl"><div className="flex items-end justify-between gap-4 px-4 pb-3 pt-4 sm:px-5 sm:pt-5"><div><p className="clan-kicker">Atividade</p><h2 className="mt-1 text-lg font-semibold text-foreground">O que precisa da tua atenção</h2></div><span className="text-[11px] text-muted-foreground">Jornal + notificações</span></div><div className="px-2 pb-2 sm:px-3 sm:pb-3">{items.length===0?<div className="flex min-h-48 flex-col items-center justify-center rounded-xl border border-dashed border-white/[0.07] bg-black/15 px-5 text-center"><Clock3 className="h-6 w-6 text-primary/65"/><p className="mt-3 text-sm font-medium text-foreground">Ainda não existem acontecimentos</p><p className="mt-1 max-w-md text-xs leading-5 text-muted-foreground">Criação do clube, resultados, transferências, recompensas e alertas operacionais aparecerão aqui.</p></div>:<div className="divide-y divide-white/[0.055]">{items.map(item=>{const content=<><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border ${item.unread?'border-primary/20 bg-primary/[.07] text-primary':'border-white/[.06] bg-black/20 text-muted-foreground'}`}>{iconFor(item.category,item.kind)}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-medium text-foreground">{item.title}</p>{item.unread&&<span className="h-1.5 w-1.5 shrink-0 rounded-full bg-primary"/>}</div><p className="mt-0.5 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.summary}</p></div><p className="shrink-0 pt-0.5 text-[10px] text-muted-foreground">{formatTimeAgo(item.date)}</p></>;return item.href?<Link key={item.id} href={item.href} className="flex items-start gap-3 rounded-xl px-2 py-3.5 transition hover:bg-white/[.025] sm:px-2.5">{content}</Link>:<div key={item.id} className="flex items-start gap-3 px-2 py-3.5 sm:px-2.5">{content}</div>})}</div>}</div></section>
}
function iconFor(category:string,kind:Item['kind']){if(kind==='NOTIFICATION')return <Bell className="h-4 w-4"/>;if(category==='MATCH')return <Trophy className="h-4 w-4"/>;if(category==='MARKET')return <ShoppingCart className="h-4 w-4"/>;if(category==='PLAYER')return <RefreshCw className="h-4 w-4"/>;return <Newspaper className="h-4 w-4"/>}
function formatTimeAgo(dateStr:string){const diffMs=Date.now()-new Date(dateStr).getTime(),mins=Math.floor(diffMs/60000),hours=Math.floor(mins/60),days=Math.floor(hours/24);if(mins<1)return'agora';if(mins<60)return`há ${mins} min`;if(hours<24)return`há ${hours} h`;if(days<7)return`há ${days} d`;return new Date(dateStr).toLocaleDateString('pt-PT')}
