import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ArrowLeft, Coins, Shield, Users } from 'lucide-react'
import { getAdminSession, canAdmin } from '@/lib/server/admin-auth'
import { AdminFreezeButton } from '@/components/admin/admin-freeze-button'

export const dynamic='force-dynamic'

export default async function AdminUsersPage(){const session=await getAdminSession();if(!session)redirect('/dashboard');const[profilesQ,clubsQ,userAccountsQ,clubAccountsQ,freezesQ]=await Promise.all([session.serviceClient.from('user_profile').select('*').order('created_at',{ascending:false}).limit(100),session.serviceClient.from('club').select('*').limit(1000),session.serviceClient.from('user_currency_account').select('user_id,currency,balance').limit(1000),session.serviceClient.from('club_currency_account').select('club_id,balance').limit(1000),session.serviceClient.from('economic_freeze').select('*').eq('scope','USER').eq('active',true)]);for(const q of[profilesQ,clubsQ,userAccountsQ,clubAccountsQ,freezesQ])if(q.error)throw q.error;const clubs=clubsQ.data??[];const clubSilver=new Map((clubAccountsQ.data??[]).map((r:any)=>[r.club_id,Number(r.balance)]));const accounts=userAccountsQ.data??[];const freezes=new Map((freezesQ.data??[]).map((r:any)=>[r.user_id,r.id]));const canFreeze=canAdmin(session.role,'FREEZE');return <div className="space-y-7"><Header/><section className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-white/[0.07] text-left text-[10px] uppercase tracking-[.13em] text-muted-foreground"><th className="pb-3">Manager</th><th className="pb-3">Clubes</th><th className="pb-3">Gold</th><th className="pb-3">Bronze</th><th className="pb-3">Reputação</th><th className="pb-3 text-right">Ações</th></tr></thead><tbody>{(profilesQ.data??[]).map((p:any)=>{const userClubs=clubs.filter((c:any)=>c.user_id===p.id);const gold=accounts.find((a:any)=>a.user_id===p.id&&a.currency==='GOLD');const bronze=accounts.find((a:any)=>a.user_id===p.id&&a.currency==='BRONZE');return <tr key={p.id} className="border-b border-white/[0.05]"><td className="py-4"><p className="font-black">{p.username}</p><p className="mt-1 text-xs text-muted-foreground">Lv.{p.manager_level} · {p.id}</p></td><td className="py-4"><p className="font-semibold">{userClubs.length}</p><p className="mt-1 text-xs text-muted-foreground">{userClubs.slice(0,2).map((c:any)=>`${c.name} (${(clubSilver.get(c.id)??0).toLocaleString('pt-PT')} S)`).join(' · ')||'—'}</p></td><td className="py-4 font-bold tabular-nums">{Number(gold?.balance??0).toLocaleString('pt-PT')}</td><td className="py-4 font-bold tabular-nums">{Number(bronze?.balance??0).toLocaleString('pt-PT')}</td><td className="py-4">{Number(p.reputation).toLocaleString('pt-PT')}</td><td className="py-4 text-right">{canFreeze&&<AdminFreezeButton scope="USER" targetId={p.id} freezeId={freezes.get(p.id)??null}/>}</td></tr>})}</tbody></table></div></section></div>}

function Header(){return <section className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><Link href="/admin" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/>Admin</Link><div className="mt-4 flex items-center gap-2"><Users className="h-5 w-5 text-primary"/><h1 className="text-2xl font-black">Utilizadores & Clubes</h1></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Shield className="h-3.5 w-3.5"/>Identidade global + clubes por universo</span><span className="inline-flex items-center gap-1"><Coins className="h-3.5 w-3.5"/>Gold/Bronze globais e Silver por clube</span></div></section>}
