import type { SupabaseClient } from '@supabase/supabase-js'
import type { CompetitionRepository } from '@/lib/application/contracts'
import type { Competition, Match, Season, UUID } from '@/lib/domain/core'
import type { CompetitionParticipant, LeagueStanding, MatchDispute, MatchSettlementReceipt } from '@/lib/domain/competition'

const n = (value: unknown) => Number(value ?? 0)
const mapSeason = (r: any): Season => ({ id:r.id, universeId:r.universe_id, name:r.name, status:r.status, startsAt:r.starts_at, endsAt:r.ends_at, registrationStartsAt:r.registration_starts_at, registrationEndsAt:r.registration_ends_at, rulesSnapshot:r.rules_snapshot ?? {}, createdAt:r.created_at })
const mapCompetition = (r:any): Competition => ({ id:r.id, universeId:r.universe_id, seasonId:r.season_id, type:r.type, name:r.name, status:r.status, rules:r.rules ?? {}, entryFee:n(r.entry_fee), prizePool:n(r.prize_pool), createdAt:r.created_at })
const mapMatch = (r:any): Match => ({ id:r.id, universeId:r.universe_id, competitionId:r.competition_id, homeClubId:r.home_club_id, awayClubId:r.away_club_id, state:r.state, scheduledAt:r.scheduled_at, homeScore:r.home_score === null ? null : n(r.home_score), awayScore:r.away_score === null ? null : n(r.away_score), submittedBy:r.submitted_by, submittedAt:r.submitted_at, confirmedAt:r.confirmed_at, settledAt:r.settled_at, resultMetadata:r.result_metadata ?? {}, createdAt:r.created_at, updatedAt:r.updated_at })

export class SupabaseCompetitionRepository implements CompetitionRepository {
  constructor(private readonly client: SupabaseClient) {}
  async getSeason(id: UUID) { const {data,error}=await this.client.from('season').select('*').eq('id',id).maybeSingle(); if(error) throw error; return data ? mapSeason(data) : null }
  async getCompetition(id: UUID) { const {data,error}=await this.client.from('competition').select('*').eq('id',id).maybeSingle(); if(error) throw error; return data ? mapCompetition(data) : null }
  async getMatch(id: UUID) { const {data,error}=await this.client.from('match').select('*').eq('id',id).maybeSingle(); if(error) throw error; return data ? mapMatch(data) : null }
  async listParticipants(competitionId: UUID): Promise<CompetitionParticipant[]> { const {data,error}=await this.client.from('competition_participant').select('*').eq('competition_id',competitionId).order('seed'); if(error) throw error; return (data??[]).map((r:any)=>({id:r.id,competitionId:r.competition_id,clubId:r.club_id,seed:r.seed,status:r.status,joinedAt:r.joined_at})) }
  async listStandings(competitionId: UUID): Promise<LeagueStanding[]> { const {data,error}=await this.client.from('league_standing').select('*').eq('competition_id',competitionId).order('points',{ascending:false}).order('goals_for',{ascending:false}); if(error) throw error; return (data??[]).map((r:any)=>({competitionId:r.competition_id,clubId:r.club_id,played:n(r.played),won:n(r.won),drawn:n(r.drawn),lost:n(r.lost),goalsFor:n(r.goals_for),goalsAgainst:n(r.goals_against),points:n(r.points),position:r.position,updatedAt:r.updated_at})) }
  async listClubMatches(clubId: UUID): Promise<Match[]> { const {data,error}=await this.client.from('match').select('*').or(`home_club_id.eq.${clubId},away_club_id.eq.${clubId}`).order('scheduled_at'); if(error) throw error; return (data??[]).map(mapMatch) }
  async submitResult(input:{matchId:UUID;homeScore:number;awayScore:number;idempotencyKey:string}):Promise<Match>{ const {data,error}=await this.client.rpc('submit_match_result',{p_match_id:input.matchId,p_home_score:input.homeScore,p_away_score:input.awayScore,p_idempotency_key:input.idempotencyKey}); if(error) throw error; return mapMatch(data) }
  async confirmResult(input:{matchId:UUID;idempotencyKey:string}):Promise<MatchSettlementReceipt>{ const {data,error}=await this.client.rpc('confirm_and_settle_match',{p_match_id:input.matchId,p_idempotency_key:input.idempotencyKey}); if(error) throw error; return {matchId:data.match_id,settlementId:data.settlement_id,version:n(data.version),homeEloDelta:n(data.home_elo_delta),awayEloDelta:n(data.away_elo_delta),standingsUpdated:Boolean(data.standings_updated),settledAt:data.settled_at} }
  async openDispute(input:{matchId:UUID;reason:string}):Promise<MatchDispute>{ const {data,error}=await this.client.rpc('open_match_dispute',{p_match_id:input.matchId,p_reason:input.reason}); if(error) throw error; return {id:data.id,matchId:data.match_id,openedBy:data.opened_by,reason:data.reason,state:data.state,resolution:data.resolution,resolvedBy:data.resolved_by,createdAt:data.created_at,resolvedAt:data.resolved_at} }
}
