'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Coins, Globe2, Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog,DialogBody,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger } from '@/components/ui/dialog'
import type { UniverseCreationPolicy } from '@/components/universos/universos-client'

const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)

export function CreateUniverseDialog({policy}:{policy:UniverseCreationPolicy}){
  const router=useRouter();const[open,setOpen]=useState(false);const[name,setName]=useState('');const[slug,setSlug]=useState('');const[description,setDescription]=useState('');const[slugTouched,setSlugTouched]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null)
  const atLimit=policy.maxOwned>0&&policy.ownedCount>=policy.maxOwned,insufficient=policy.goldBalance<policy.goldCost
  async function submit(event:React.FormEvent){event.preventDefault();if(loading)return;setLoading(true);setError(null);try{const response=await fetch('/api/universes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,slug,description,idempotencyKey:`universe:${crypto.randomUUID()}`})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Não foi possível criar o universo.');const universeId=payload.result?.universe?.id;if(!universeId)throw new Error('A operação terminou sem devolver o universo criado.');setOpen(false);router.refresh();router.push(`/onboarding?universe=${encodeURIComponent(universeId)}`)}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o universo.')}finally{setLoading(false)}}
  if(!policy.enabled)return <div className="rounded-xl border border-white/[.07] bg-black/20 px-4 py-3 text-xs text-muted-foreground"><p className="font-bold text-foreground">Criação governada</p><p className="mt-1">A política ainda não está ativa na base de dados atual.</p></div>
  return <Dialog open={open} onOpenChange={value=>{if(!loading){setOpen(value);setError(null)}}}><DialogTrigger asChild><Button disabled={atLimit||insufficient}><Plus className="h-4 w-4"/>Criar universo</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Criar universo comunitário</DialogTitle><DialogDescription>Operação governada: ownership, limite, Gold e ledger são validados atomicamente no servidor.</DialogDescription></DialogHeader><DialogBody><div className="grid gap-3 sm:grid-cols-3"><Info icon={Coins} label="Custo" value={`${policy.goldCost.toLocaleString('pt-PT')} Gold`}/><Info icon={Coins} label="Saldo" value={`${policy.goldBalance.toLocaleString('pt-PT')} Gold`}/><Info icon={Globe2} label="Limite" value={`${policy.ownedCount}/${policy.maxOwned}`}/></div><form id="create-universe-form" onSubmit={submit} className="mt-5 space-y-4"><Field label="Nome do universo"><input required minLength={3} maxLength={50} value={name} onChange={event=>{setName(event.target.value);if(!slugTouched)setSlug(slugify(event.target.value))}} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3.5 text-sm outline-none focus:border-primary/45" placeholder="Liga dos Fundadores"/></Field><Field label="Identificador"><input required minLength={3} maxLength={48} value={slug} onChange={event=>{setSlugTouched(true);setSlug(slugify(event.target.value))}} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3.5 font-mono text-sm outline-none focus:border-primary/45" placeholder="liga-dos-fundadores"/><p className="mt-1 text-[10px] text-muted-foreground">Usado em referências internas e deve ser único.</p></Field><Field label="Descrição"><textarea value={description} onChange={event=>setDescription(event.target.value.slice(0,500))} rows={4} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm outline-none focus:border-primary/45" placeholder="Objetivo, comunidade e regras gerais deste universo."/><p className="mt-1 text-right text-[10px] text-muted-foreground">{description.length}/500</p></Field>{error&&<p className="rounded-xl border border-destructive/20 bg-destructive/[.06] p-3 text-xs text-destructive">{error}</p>}</form></DialogBody><DialogFooter><Button type="button" variant="ghost" disabled={loading} onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" form="create-universe-form" disabled={loading||name.trim().length<3||slug.length<3}>{loading?'A criar…':`Criar por ${policy.goldCost.toLocaleString('pt-PT')} Gold`}</Button></DialogFooter></DialogContent></Dialog>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-bold text-muted-foreground">{label}</span>{children}</label>}
function Info({icon:Icon,label,value}:{icon:typeof Coins;label:string;value:string}){return <div className="rounded-xl border border-white/[.07] bg-black/20 p-3"><Icon className="h-4 w-4 text-primary"/><p className="mt-2 text-[9px] font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
