import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createApplicationServices } from '@/lib/infrastructure/repositories/supabase/factory'
import type { CommunityVisibility } from '@/lib/domain/social'

export const runtime='nodejs'

const text=(v:unknown)=>typeof v==='string'?v.trim():''
export async function POST(request:Request){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user||user.is_anonymous)return NextResponse.json({error:'authentication_required'},{status:401});let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>}catch{return NextResponse.json({error:'invalid_json'},{status:400})}const action=text(body.action);const services=createApplicationServices(supabase);try{if(action==='create-community'){const name=text(body.name),slug=text(body.slug).toLowerCase(),description=text(body.description),visibility=text(body.visibility) as CommunityVisibility;if(!name||!slug||!['PUBLIC','PRIVATE','INVITE_ONLY','APPROVAL_REQUIRED'].includes(visibility))throw new Error('invalid_community');const community=await services.social.createCommunity({name,slug,description:description||null,visibility});return NextResponse.json({community})}if(action==='join-community'){const communityId=text(body.communityId);if(!communityId)throw new Error('community_id_required');const membership=await services.social.joinCommunity(communityId);return NextResponse.json({membership})}if(action==='create-post'){const communityId=text(body.communityId),postBody=text(body.body);if(!communityId||postBody.length<2)throw new Error('invalid_post');const post=await services.social.createPost({communityId,body:postBody});return NextResponse.json({post})}if(action==='send-message'){const conversationId=text(body.conversationId),message=text(body.body);if(!conversationId||!message)throw new Error('invalid_message');const result=await services.social.sendMessage({conversationId,body:message});return NextResponse.json({message:result})}if(action==='start-direct'){const username=text(body.username);if(username.length<2)throw new Error('username_required');const{data:profile,error}=await supabase.from('user_profile').select('id').eq('username',username).maybeSingle();if(error)throw error;if(!profile)throw new Error('user_not_found');const conversation=await services.social.startDirectConversation(profile.id);return NextResponse.json({conversation})}return NextResponse.json({error:'unsupported_social_action'},{status:400})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'social_operation_failed'},{status:409})}}
