'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, FileSearch, LockKeyhole, Radar, ShieldAlert, UnlockKeyhole, UserCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ConfirmationDialog } from '@/components/ui/confirmation-dialog'

type Row=Record<string,any>
const transitions:Record<string,string[]>={OPEN:['INVESTIGATING','DISMISSED'],INVESTIGATING:['ACTION_REQUIRED','RESOLVED','DISMISSED'],ACTION_REQUIRED:['INVESTIGATING','RESOLVED','DISMISSED'],RESOLVED:['OPEN'],DISMISSED:['OPEN']}

export function ModerationCaseDetail({item,freezes,audit,targetUser,targetClub,targetUniverse,targetMatch,currentUserId,canFreeze}:{item:Row;freezes:Row[];audit:Row[];targetUser:Row|null;targetClub:Row|null;targetUniverse:Row|null;targetMatch:Row|null;currentUserId:string;canFreeze:boolean}){
  const router=useRouter();const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[pendingStatus,setPendingStatus]=useState<string|null>(null);const[pendingRelease,setPendingRelease]=useState<Row|null>(null);const[reason,setReason]=useState('');const[evidenceDescription,setEvidenceDescription]=useState('');const[evidenceUrl,setEvidenceUrl]=useState('');const[evidenceReason,setEvidenceReason]=useState('');const[signalKey,setSignalKey]=useState('');const[signalValue,setSignalValue]=useState('');const[signalReason,setSignalReason]=useState('');const[freezeReason,setFreezeReason]=useState('')
  async function call(payload:Record<string,unknown>){setLoading(true);setError(null);try{const response=await fetch('/api/admin/governance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'admin_operation_failed');router.refresh();return true}catch(e){setError(e instanceof Error?e.message:'admin_operation_failed');return false}finally{setLoading(false)}}
  async function claim(){await call({action:'moderation-update',caseId:item.id,status:item.status==='OPEN'?'INVESTIGATING':item.status,assignedAdminId:currentUserId,reason:'Caso assumido para investigação.'})}
  async function updateStatus(){if(!pendingStatus||reason.trim().length<5)return;const resolution=['RESOLVED','DISMISSED'].includes(pendingStatus)?{summary:reason.trim(),decision:pendingStatus}:null;const ok=await call({action:'moderation-update',caseId:item.id,status:pendingStatus,assignedAdminId:item.assigned_admin_id??currentUserId,resolution,reason:reason.trim()});if(ok){setPendingStatus(null);setReason('')}}
  async function addEvidence(event:React.FormEvent){event.preventDefault();if(evidenceDescription.trim().length<2||evidenceReason.trim().length<5)return;const ok=await call({action:'moderation-evidence',caseId:item.id,evidence:{type:'MANUAL',description:evidenceDescription.trim(),url:evidenceUrl.trim()||null},reason:evidenceReason.trim()});if(ok){setEvidenceDescription('');setEvidenceUrl('');setEvidenceReason('')}}
  async function addSignal(event:React.FormEvent){event.preventDefault();if(signalKey.trim().length<2||signalReason.trim().length<5)return;let value:unknown=signalValue.trim();try{value=JSON.parse(signalValue)}catch{}const ok=await call({action:'moderation-signal',caseId:item.id,signalKey:signalKey.trim(),signalValue:value,reason:signalReason.trim()});if(ok){setSignalKey('');setSignalValue('');setSignalReason('')}}
  async function freeze(scope:'USER'|'CLUB'|'UNIVERSE',targetId:string){if(freezeReason.trim().length<5)return;const ok=await call({action:'freeze-create',scope,targetId,caseId:item.id,reason:freezeReason.trim()});if(ok)setFreezeReason('')}
  async function release(){if(!pendingRelease||reason.trim().length<5)return;const ok=await call({action:'freeze-release',freezeId:pendingRelease.id,reason:reason.trim()});if(ok){setPendingRelease(null);setReason('')}}
  const activeFreezes=freezes.filter(f=>f.active)
  return <div className="space-y-6"><section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-6"><Link href="/admin/backoffice" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/>Backoffice</Link><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Status value={item.status}/><span className="text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{item.case_type} · {item.severity}</span></div><h1 className="mt-3 text-2xl font-black">{item.summary}</h1><p className="mt-2 text-xs text-muted-foreground">Caso {item.id} · criado {new Date(item.created_at).toLocaleString('pt-PT')}</p></div>{item.assigned_admin_id!==currentUserId&&!['RESOLVED','DISMISSED'].includes(item.status)&&<Button size="sm" onClick={claim} disabled={loading}><UserCheck className="h-4 w-4"/>Assumir investigação</Button>}</div></section>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-4"><Panel title="Evidências" icon={FileSearch}><div className="space-y-2">{(item.evidence??[]).map((evidence:any,index:number)=><div key={index} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{evidence.type??'EVIDENCE'}</p>{evidence.added_at&&<span className="text-[9px] text-muted-foreground">{new Date(evidence.added_at).toLocaleString('pt-PT')}</span>}</div><p className="mt-2 text-sm">{evidence.description??JSON.stringify(evidence)}</p>{evidence.url&&<a href={evidence.url} target="_blank" rel="noreferrer" className="mt-2 inline-block break-all text-xs text-primary hover:underline">{evidence.url}</a>}</div>)}{(!item.evidence||item.evidence.length===0)&&<p className="py-6 text-center text-sm text-muted-foreground">Ainda sem evidências anexadas.</p>}</div><form onSubmit={addEvidence} className="mt-4 space-y-2 border-t border-white/[.06] pt-4"><textarea value={evidenceDescription} onChange={e=>setEvidenceDescription(e.target.value)} rows={3} placeholder="Descrição da evidência" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3 py-2.5 text-sm"/><input value={evidenceUrl} onChange={e=>setEvidenceUrl(e.target.value)} placeholder="URL / referência (opcional)" className="h-10 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"/><input value={evidenceReason} onChange={e=>setEvidenceReason(e.target.value)} placeholder="Motivo para adicionar evidência" className="h-10 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"/><div className="flex justify-end"><Button type="submit" size="sm" variant="outline" disabled={loading||evidenceDescription.trim().length<2||evidenceReason.trim().length<5}>Adicionar evidência</Button></div></form></Panel>
      <Panel title="Sinais de risco / fraude" icon={Radar}><div className="space-y-2">{Object.entries(item.signals??{}).map(([key,value])=><div key={key} className="grid gap-2 rounded-xl border border-white/[.06] bg-black/20 p-3 sm:grid-cols-[160px_1fr]"><p className="text-xs font-black text-primary">{key}</p><pre className="overflow-x-auto whitespace-pre-wrap text-[10px] text-muted-foreground">{JSON.stringify(value,null,2)}</pre></div>)}{Object.keys(item.signals??{}).length===0&&<p className="py-6 text-center text-sm text-muted-foreground">Sem sinais registados.</p>}</div><form onSubmit={addSignal} className="mt-4 grid gap-2 border-t border-white/[.06] pt-4 sm:grid-cols-2"><input value={signalKey} onChange={e=>setSignalKey(e.target.value)} placeholder="Chave do sinal" className="h-10 rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"/><input value={signalValue} onChange={e=>setSignalValue(e.target.value)} placeholder="Valor ou JSON" className="h-10 rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"/><input value={signalReason} onChange={e=>setSignalReason(e.target.value)} placeholder="Motivo" className="h-10 rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm sm:col-span-2"/><div className="sm:col-span-2 sm:text-right"><Button type="submit" size="sm" variant="outline" disabled={loading||signalKey.trim().length<2||signalReason.trim().length<5}>Registar sinal</Button></div></form></Panel></div>
      <div className="space-y-4"><Panel title="Alvos" icon={ShieldAlert}><Info label="Utilizador" value={targetUser?.username??item.target_user_id??'—'}/><Info label="Clube" value={targetClub?.name??item.target_club_id??'—'}/><Info label="Universo" value={targetUniverse?.name??item.target_universe_id??'—'}/><Info label="Partida" value={targetMatch?`${targetMatch.state} · ${targetMatch.home_score??'—'}-${targetMatch.away_score??'—'}`:item.match_id??'—'}/><Info label="Responsável" value={item.assigned_admin_id??'Por atribuir'}/></Panel>
      <Panel title="Lifecycle" icon={ShieldAlert}><div className="grid gap-2">{(transitions[item.status]??[]).map(status=><Button key={status} size="sm" variant="outline" onClick={()=>{setPendingStatus(status);setReason('')}}>{status.replaceAll('_',' ')}</Button>)}</div>{item.resolution&&<div className="mt-4 rounded-xl border border-primary/10 bg-primary/[.025] p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-primary">Resolução</p><pre className="mt-2 whitespace-pre-wrap text-xs text-muted-foreground">{JSON.stringify(item.resolution,null,2)}</pre></div>}{error&&<p className="mt-3 text-xs text-destructive">{error}</p>}</Panel>
      {canFreeze&&<Panel title="Proteção económica" icon={LockKeyhole}><textarea value={freezeReason} onChange={e=>setFreezeReason(e.target.value)} rows={3} placeholder="Motivo obrigatório para freeze…" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3 py-2.5 text-sm"/><div className="mt-3 grid gap-2">{item.target_user_id&&<Button size="sm" variant="outline" disabled={loading||freezeReason.trim().length<5||activeFreezes.some(f=>f.scope==='USER')} onClick={()=>freeze('USER',item.target_user_id)}>Freeze utilizador</Button>}{item.target_club_id&&<Button size="sm" variant="outline" disabled={loading||freezeReason.trim().length<5||activeFreezes.some(f=>f.scope==='CLUB')} onClick={()=>freeze('CLUB',item.target_club_id)}>Freeze clube</Button>}{item.target_universe_id&&<Button size="sm" variant="outline" disabled={loading||freezeReason.trim().length<5||activeFreezes.some(f=>f.scope==='UNIVERSE')} onClick={()=>freeze('UNIVERSE',item.target_universe_id)}>Freeze universo</Button>}</div><div className="mt-4 space-y-2">{activeFreezes.map(freezeItem=><div key={freezeItem.id} className="rounded-xl border border-destructive/15 bg-destructive/[.035] p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black text-destructive">{freezeItem.scope} bloqueado</p><p className="mt-1 text-[10px] text-muted-foreground">{freezeItem.reason}</p></div><Button size="sm" variant="outline" onClick={()=>{setPendingRelease(freezeItem);setReason('')}}><UnlockKeyhole className="h-3.5 w-3.5"/>Libertar</Button></div></div>)}</div></Panel>}</div></section>
    <Panel title="Audit trail" icon={Radar}><div className="divide-y divide-white/[.06]">{audit.map(event=><div key={event.id} className="py-3"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs font-bold">{event.action.replaceAll('_',' ')}</p><span className="text-[10px] text-muted-foreground">{new Date(event.created_at).toLocaleString('pt-PT')}</span></div>{event.reason&&<p className="mt-1 text-xs text-muted-foreground">{event.reason}</p>}</div>)}{audit.length===0&&<p className="py-8 text-center text-sm text-muted-foreground">Sem eventos.</p>}</div></Panel>
    <ConfirmationDialog open={Boolean(pendingStatus)} onOpenChange={open=>{if(!open&&!loading)setPendingStatus(null)}} title={`Alterar caso para ${pendingStatus?.replaceAll('_',' ')??''}`} description="A transição fica auditada. Para RESOLVED/DISMISSED, o motivo é também guardado como decisão." confirmLabel="Confirmar decisão" tone={['RESOLVED','DISMISSED'].includes(pendingStatus??'')?'warning':'default'} isLoading={loading} onConfirm={updateStatus}><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} placeholder="Motivo / decisão…" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm"/></ConfirmationDialog>
    <ConfirmationDialog open={Boolean(pendingRelease)} onOpenChange={open=>{if(!open&&!loading)setPendingRelease(null)}} title="Libertar freeze económico" description={pendingRelease?.reason} confirmLabel="Libertar" tone="warning" isLoading={loading} onConfirm={release}><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} placeholder="Motivo obrigatório…" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm"/></ConfirmationDialog>
  </div>
}
function Status({value}:{value:string}){return <span className="rounded-md border border-destructive/15 bg-destructive/[.04] px-2 py-1 text-[9px] font-black uppercase tracking-[.12em] text-destructive">{value.replaceAll('_',' ')}</span>}
function Panel({title,icon:Icon,children}:{title:string;icon:typeof ShieldAlert;children:React.ReactNode}){return <section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary"/><h2 className="font-black">{title}</h2></div><div className="mt-4">{children}</div></section>}
function Info({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4 border-b border-white/[.05] py-2.5 last:border-0"><span className="text-xs text-muted-foreground">{label}</span><span className="max-w-[65%] break-all text-right text-xs font-bold">{value}</span></div>}
