'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Clock3, FileText, Headphones, MessageSquareText, UserCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ConfirmationDialog } from '@/components/ui/confirmation-dialog'

type Row=Record<string,any>
const transitions:Record<string,string[]>={OPEN:['IN_PROGRESS','CLOSED'],IN_PROGRESS:['WAITING_USER','WAITING_INTERNAL','RESOLVED','CLOSED'],WAITING_USER:['IN_PROGRESS','WAITING_INTERNAL','RESOLVED','CLOSED'],WAITING_INTERNAL:['IN_PROGRESS','WAITING_USER','RESOLVED','CLOSED'],RESOLVED:['IN_PROGRESS','CLOSED'],CLOSED:['OPEN']}

export function SupportTicketDetail({ticket,notes,audit,requester,club,universe,currentUserId}:{ticket:Row;notes:Row[];audit:Row[];requester:Row|null;club:Row|null;universe:Row|null;currentUserId:string}){
  const router=useRouter();const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[pendingStatus,setPendingStatus]=useState<string|null>(null);const[reason,setReason]=useState('');const[reply,setReply]=useState('');const[note,setNote]=useState('');const[priority,setPriority]=useState(ticket.priority);const[priorityReason,setPriorityReason]=useState('')
  async function call(payload:Record<string,unknown>){setLoading(true);setError(null);try{const response=await fetch('/api/admin/governance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'admin_operation_failed');router.refresh();return true}catch(e){setError(e instanceof Error?e.message:'admin_operation_failed');return false}finally{setLoading(false)}}
  async function claim(){await call({action:'ticket-update',ticketId:ticket.id,status:ticket.status==='OPEN'?'IN_PROGRESS':ticket.status,assignedAdminId:currentUserId,reason:'Ticket assumido pelo operador.'})}
  async function confirmStatus(){if(!pendingStatus||reason.trim().length<5)return;const ok=await call({action:'ticket-update',ticketId:ticket.id,status:pendingStatus,assignedAdminId:ticket.assigned_admin_id??currentUserId,reason:reason.trim()});if(ok){setPendingStatus(null);setReason('')}}
  async function sendPublic(event:React.FormEvent){event.preventDefault();if(reply.trim().length<2)return;const ok=await call({action:'ticket-reply',ticketId:ticket.id,body:reply.trim()});if(ok)setReply('')}
  async function sendInternal(event:React.FormEvent){event.preventDefault();if(note.trim().length<2)return;const ok=await call({action:'ticket-note',ticketId:ticket.id,body:note.trim(),internal:true});if(ok)setNote('')}
  async function changePriority(){if(priorityReason.trim().length<5)return;const ok=await call({action:'ticket-priority',ticketId:ticket.id,priority,reason:priorityReason.trim()});if(ok)setPriorityReason('')}
  return <div className="space-y-6"><section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-6"><Link href="/admin/backoffice" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/>Backoffice</Link><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Status value={ticket.status}/><span className="text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{ticket.category} · {ticket.priority}</span></div><h1 className="mt-3 text-2xl font-black">{ticket.subject}</h1><p className="mt-2 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{ticket.description}</p></div><div className="flex gap-2">{ticket.assigned_admin_id!==currentUserId&&!['RESOLVED','CLOSED'].includes(ticket.status)&&<Button size="sm" onClick={claim} disabled={loading}><UserCheck className="h-4 w-4"/>Assumir</Button>}</div></div></section>
    <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-4"><Panel title="Conversa" icon={MessageSquareText}><div className="space-y-3">{notes.map(item=><div key={item.id} className={`rounded-xl border p-3 ${item.internal?'border-amber-400/15 bg-amber-400/[.035]':'border-white/[.06] bg-black/20'}`}><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.11em] text-muted-foreground">{item.internal?'Nota interna':item.author_user_id===ticket.requester_user_id?'Utilizador':'Resposta pública'}</p><span className="text-[9px] text-muted-foreground">{new Date(item.created_at).toLocaleString('pt-PT')}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{item.body}</p></div>)}{notes.length===0&&<p className="py-6 text-center text-sm text-muted-foreground">Sem mensagens adicionais.</p>}</div></Panel>
      {!['RESOLVED','CLOSED'].includes(ticket.status)&&<Panel title="Responder ao utilizador" icon={Headphones}><form onSubmit={sendPublic}><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={5} placeholder="Resposta visível ao utilizador…" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm outline-none focus:border-primary/45"/><div className="mt-3 flex justify-end"><Button type="submit" size="sm" disabled={loading||reply.trim().length<2}>Enviar e aguardar utilizador</Button></div></form></Panel>}
      <Panel title="Nota interna" icon={FileText}><form onSubmit={sendInternal}><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Contexto apenas para a equipa…" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm outline-none focus:border-primary/45"/><div className="mt-3 flex justify-end"><Button type="submit" size="sm" variant="outline" disabled={loading||note.trim().length<2}>Guardar nota interna</Button></div></form></Panel></div>
      <div className="space-y-4"><Panel title="Contexto" icon={Headphones}><Info label="Utilizador" value={requester?.username??ticket.requester_user_id??'—'}/><Info label="Reputação" value={requester?.reputation!=null?String(requester.reputation):'—'}/><Info label="Clube" value={club?.name??'—'}/><Info label="Universo" value={universe?.name??'—'}/><Info label="Criado" value={new Date(ticket.created_at).toLocaleString('pt-PT')}/><Info label="Responsável" value={ticket.assigned_admin_id??'Por atribuir'}/></Panel>
      <Panel title="Operação" icon={Clock3}><label className="block text-xs font-bold text-muted-foreground">Prioridade</label><select value={priority} onChange={e=>setPriority(e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm">{['LOW','NORMAL','HIGH','CRITICAL'].map(v=><option key={v}>{v}</option>)}</select><input value={priorityReason} onChange={e=>setPriorityReason(e.target.value)} placeholder="Motivo da alteração" className="mt-2 h-10 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"/><Button size="sm" variant="outline" className="mt-2 w-full" disabled={loading||priority===ticket.priority||priorityReason.trim().length<5} onClick={changePriority}>Atualizar prioridade</Button><div className="my-4 h-px bg-white/[.06]"/><p className="text-xs font-bold text-muted-foreground">Próximo estado</p><div className="mt-2 grid gap-2">{(transitions[ticket.status]??[]).map(status=><Button key={status} size="sm" variant="outline" onClick={()=>{setPendingStatus(status);setReason('')}}>{label(status)}</Button>)}</div>{error&&<p className="mt-3 text-xs text-destructive">{error}</p>}</Panel></div></section>
    <Panel title="Histórico auditado" icon={Clock3}><div className="divide-y divide-white/[.06]">{audit.map(item=><div key={item.id} className="py-3"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs font-bold">{item.action.replaceAll('_',' ')}</p><span className="text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleString('pt-PT')}</span></div>{item.reason&&<p className="mt-1 text-xs text-muted-foreground">{item.reason}</p>}</div>)}{audit.length===0&&<p className="py-8 text-center text-sm text-muted-foreground">Sem eventos de auditoria.</p>}</div></Panel>
    <ConfirmationDialog open={Boolean(pendingStatus)} onOpenChange={open=>{if(!open&&!loading)setPendingStatus(null)}} title={`Alterar estado para ${pendingStatus?label(pendingStatus):''}`} description="A transição fica registada no audit log e deve ter um motivo operacional." confirmLabel="Confirmar alteração" tone={pendingStatus==='CLOSED'?'warning':'default'} isLoading={loading} onConfirm={confirmStatus}><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} placeholder="Motivo obrigatório…" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm outline-none focus:border-primary/45"/>{reason.trim().length>0&&reason.trim().length<5&&<p className="mt-2 text-xs text-destructive">Usa pelo menos 5 caracteres.</p>}</ConfirmationDialog>
  </div>
}
function label(value:string){return value.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}
function Status({value}:{value:string}){return <span className="rounded-md border border-primary/15 bg-primary/[.05] px-2 py-1 text-[9px] font-black uppercase tracking-[.12em] text-primary">{value.replaceAll('_',' ')}</span>}
function Panel({title,icon:Icon,children}:{title:string;icon:typeof Headphones;children:React.ReactNode}){return <section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary"/><h2 className="font-black">{title}</h2></div><div className="mt-4">{children}</div></section>}
function Info({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4 border-b border-white/[.05] py-2.5 last:border-0"><span className="text-xs text-muted-foreground">{label}</span><span className="max-w-[65%] break-all text-right text-xs font-bold">{value}</span></div>}
