'use client'

import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Clock3, Flag, Search, Settings2, SlidersHorizontal } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog,DialogBody,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog'
import { ConfirmationDialog } from '@/components/ui/confirmation-dialog'

type FlagItem={key:string;enabled:boolean;scope:'GLOBAL'|'ENVIRONMENT'|'UNIVERSE'|'COHORT';scope_reference:string|null;configuration:Record<string,unknown>}
type ConfigItem={key:string;category:string;value:unknown;version:number;effective_from:string;updated_at:string}
type HistoryItem={id:number;key:string;category:string;value:unknown;version:number;effective_from:string;reason:string;created_at:string}
type Meta={title:string;description:string}
const META:Record<string,Meta>={
  'players.provider':{title:'Fornecedor de jogadores',description:'Origem e dimensão dos lotes usados para sincronizar o catálogo.'},
  'players.valuation.default':{title:'Valorização base dos jogadores',description:'Fatores usados para materializar preço, valor de mercado e salário.'},
  'players.starter':{title:'Faixa do plantel inicial',description:'Overall mínimo e máximo elegível para o starter squad.'},
  'universes.community_creation':{title:'Criação de universos comunitários',description:'Ativa a criação governada e controla custo em Gold, limite por manager e defaults económicos.'},
}
const human=(value:string)=>value.replaceAll('.',' · ').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const isRecord=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value)
const isPrimitiveRecord=(value:unknown):value is Record<string,string|number|boolean|null>=>isRecord(value)&&Object.values(value).every(item=>['string','number','boolean'].includes(typeof item)||item===null)

export function AdminConfigClient({flags,configs,history}:{flags:FlagItem[];configs:ConfigItem[];history:HistoryItem[]}){
  const router=useRouter();const[query,setQuery]=useState('');const[category,setCategory]=useState('ALL');const[pendingFlag,setPendingFlag]=useState<FlagItem|null>(null);const[pendingConfig,setPendingConfig]=useState<ConfigItem|null>(null);const[draft,setDraft]=useState<unknown>(null);const[jsonDraft,setJsonDraft]=useState('');const[advanced,setAdvanced]=useState(false);const[reason,setReason]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null)
  const categories=useMemo(()=>['ALL',...Array.from(new Set(configs.map(item=>item.category)))],[configs])
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return configs.filter(item=>(category==='ALL'||item.category===category)&&(!needle||`${item.key} ${META[item.key]?.title??''} ${item.category}`.toLowerCase().includes(needle)))},[configs,query,category])
  const activeFlags=flags.filter(item=>item.enabled).length
  function edit(config:ConfigItem){setPendingConfig(config);setDraft(config.value);setJsonDraft(JSON.stringify(config.value,null,2));setAdvanced(!isPrimitiveRecord(config.value));setReason('');setError(null)}
  function updateField(key:string,raw:string,type:string){setDraft((current:unknown)=>{const source=isRecord(current)?current:{};let value:unknown=raw;if(type==='number')value=raw===''?0:Number(raw);if(type==='boolean')value=raw==='true';return{...source,[key]:value}})}
  async function saveConfig(){if(!pendingConfig||reason.trim().length<5)return;let value=draft;if(advanced){try{value=JSON.parse(jsonDraft)}catch{setError('O JSON avançado não é válido.');return}}setLoading(true);setError(null);try{const response=await fetch('/api/admin/governance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'platform-config-update',key:pendingConfig.key,category:pendingConfig.category,value,reason:reason.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'configuration_update_failed');setPendingConfig(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:'configuration_update_failed')}finally{setLoading(false)}}
  async function toggleFlag(){if(!pendingFlag||reason.trim().length<5)return;setLoading(true);setError(null);try{const response=await fetch('/api/admin/governance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'feature-flag-update',key:pendingFlag.key,enabled:!pendingFlag.enabled,scope:pendingFlag.scope,scopeReference:pendingFlag.scope_reference,configuration:pendingFlag.configuration,reason:reason.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'configuration_update_failed');setPendingFlag(null);setReason('');router.refresh()}catch(e){setError(e instanceof Error?e.message:'configuration_update_failed')}finally{setLoading(false)}}
  return <div className="space-y-6">
    <section className="grid gap-3 sm:grid-cols-3"><Metric icon={Settings2} label="Configurações" value={configs.length} detail={`${categories.length-1} categorias`}/><Metric icon={Flag} label="Flags ativas" value={activeFlags} detail={`${flags.length} definidas`}/><Metric icon={Clock3} label="Versões arquivadas" value={history.length} detail="últimas alterações"/></section>
    <section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2"><SlidersHorizontal className="h-5 w-5 text-primary"/><h2 className="text-xl font-black">Parâmetros operacionais</h2></div><p className="mt-1 text-xs text-muted-foreground">Pesquisa e edita a configuração por intenção, sem trabalhar diretamente com JSON na maioria dos casos.</p></div><label className="relative min-w-[260px]"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar configuração" className="h-10 w-full rounded-xl border border-white/[.08] bg-black/25 pl-9 pr-3 text-sm outline-none focus:border-primary/45"/></label></div><div className="mt-4 flex flex-wrap gap-2">{categories.map(item=><button key={item} type="button" onClick={()=>setCategory(item)} className={`rounded-lg border px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.1em] transition ${category===item?'border-primary/20 bg-primary/[.08] text-primary':'border-white/[.07] bg-black/20 text-muted-foreground hover:text-foreground'}`}>{item==='ALL'?'Tudo':human(item)}</button>)}</div><div className="mt-5 grid gap-3 xl:grid-cols-2">{filtered.map(config=>{const meta=META[config.key]??{title:human(config.key),description:'Parâmetro versionado da plataforma.'};return <article key={config.key} className="rounded-xl border border-white/[.07] bg-black/20 p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.13em] text-primary">{config.category}</p><h3 className="mt-1 font-black">{meta.title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{meta.description}</p></div><span className="shrink-0 rounded-md border border-white/[.07] px-2 py-1 text-[9px] text-muted-foreground">v{config.version}</span></div><div className="mt-4 rounded-lg border border-white/[.05] bg-[#090909] p-3">{summary(config.value)}</div><div className="mt-4 flex items-center justify-between gap-3"><p className="font-mono text-[9px] text-muted-foreground">{config.key}</p><Button size="sm" variant="outline" onClick={()=>edit(config)}>Configurar</Button></div></article>})}{filtered.length===0&&<p className="py-12 text-center text-sm text-muted-foreground xl:col-span-2">Sem configurações para os filtros atuais.</p>}</div></section>
    <section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-6"><div className="flex items-center gap-2"><Flag className="h-5 w-5 text-primary"/><h2 className="text-xl font-black">Feature flags</h2></div><p className="mt-1 text-xs text-muted-foreground">Interruptores de rollout. Alterações continuam a exigir motivo e auditoria.</p><div className="mt-5 grid gap-3 lg:grid-cols-2">{flags.map(flag=><article key={flag.key} className="flex items-center justify-between gap-4 rounded-xl border border-white/[.07] bg-black/20 p-4"><div><p className="text-sm font-black">{human(flag.key)}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{flag.key} · {flag.scope}{flag.scope_reference?` · ${flag.scope_reference}`:''}</p></div><Button size="sm" variant={flag.enabled?'outline':'default'} onClick={()=>{setPendingFlag(flag);setReason('');setError(null)}}>{flag.enabled?'Desativar':'Ativar'}</Button></article>)}{flags.length===0&&<p className="py-8 text-center text-sm text-muted-foreground lg:col-span-2">Sem feature flags.</p>}</div></section>
    <section className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5 sm:p-6"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-primary"/><h2 className="text-xl font-black">Histórico de configuração</h2></div><div className="mt-5 divide-y divide-white/[.06] border-y border-white/[.06]">{history.map(item=><div key={item.id} className="py-3"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black">{META[item.key]?.title??human(item.key)} <span className="text-muted-foreground">· v{item.version}</span></p><p className="mt-1 text-[10px] text-muted-foreground">{item.reason}</p></div><span className="text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleString('pt-PT')}</span></div></div>)}{history.length===0&&<p className="py-8 text-center text-sm text-muted-foreground">Ainda não existem versões arquivadas.</p>}</div></section>
    <Dialog open={Boolean(pendingConfig)} onOpenChange={open=>{if(!open&&!loading)setPendingConfig(null)}}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{pendingConfig?META[pendingConfig.key]?.title??human(pendingConfig.key):'Configuração'}</DialogTitle><DialogDescription>{pendingConfig?.key} · versão atual {pendingConfig?.version}</DialogDescription></DialogHeader><DialogBody>{pendingConfig&&<div className="space-y-4"><div className="flex items-center justify-between rounded-xl border border-white/[.07] bg-black/20 p-3"><div><p className="text-xs font-bold">Modo de edição</p><p className="mt-1 text-[10px] text-muted-foreground">{advanced?'JSON avançado':'Campos estruturados'}</p></div><Button size="sm" variant="outline" onClick={()=>{if(advanced){try{const parsed=JSON.parse(jsonDraft);setDraft(parsed);setAdvanced(false);setError(null)}catch{setError('Corrige o JSON antes de regressar aos campos.')}}else{setJsonDraft(JSON.stringify(draft,null,2));setAdvanced(true)}}}>{advanced?'Usar campos':'Modo JSON'}</Button></div>{advanced?<textarea value={jsonDraft} onChange={e=>setJsonDraft(e.target.value)} rows={12} className="w-full resize-y rounded-xl border border-white/[.08] bg-[#0a0a0a] px-3.5 py-3 font-mono text-xs outline-none focus:border-primary/45"/>:isPrimitiveRecord(draft)?<div className="grid gap-3 sm:grid-cols-2">{Object.entries(draft).map(([key,value])=><PrimitiveField key={key} name={key} value={value} onChange={(raw,type)=>updateField(key,raw,type)}/>)}</div>:<p className="text-xs text-muted-foreground">Este valor requer o modo JSON.</p>}<label className="block"><span className="mb-2 block text-xs font-bold text-muted-foreground">Motivo obrigatório</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm" placeholder="Explica por que esta configuração está a mudar."/></label>{error&&<p className="text-xs text-destructive">{error}</p>}</div>}</DialogBody><DialogFooter><Button type="button" variant="ghost" onClick={()=>setPendingConfig(null)} disabled={loading}>Cancelar</Button><Button type="button" onClick={saveConfig} disabled={loading||reason.trim().length<5}>{loading?'A guardar…':'Guardar nova versão'}</Button></DialogFooter></DialogContent></Dialog>
    <ConfirmationDialog open={Boolean(pendingFlag)} onOpenChange={open=>{if(!open&&!loading)setPendingFlag(null)}} title={`${pendingFlag?.enabled?'Desativar':'Ativar'} ${pendingFlag?human(pendingFlag.key):''}`} description="A alteração é imediata e fica registada no audit log." confirmLabel={pendingFlag?.enabled?'Desativar flag':'Ativar flag'} tone="warning" isLoading={loading} onConfirm={toggleFlag}><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#111] px-3.5 py-3 text-sm" placeholder="Motivo obrigatório…"/>{error&&<p className="mt-2 text-xs text-destructive">{error}</p>}</ConfirmationDialog>
  </div>
}
function PrimitiveField({name,value,onChange}:{name:string;value:string|number|boolean|null;onChange:(raw:string,type:string)=>void}){const type=typeof value;if(type==='boolean')return <label className="block"><span className="mb-2 block text-xs font-bold text-muted-foreground">{human(name)}</span><select value={String(value)} onChange={e=>onChange(e.target.value,'boolean')} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3 text-sm"><option value="true">Ativo</option><option value="false">Inativo</option></select></label>;return <label className="block"><span className="mb-2 block text-xs font-bold text-muted-foreground">{human(name)}</span><input type={type==='number'?'number':'text'} value={value==null?'':String(value)} onChange={e=>onChange(e.target.value,type)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#111] px-3.5 text-sm outline-none focus:border-primary/45"/></label>}
function summary(value:unknown){if(isPrimitiveRecord(value)){const entries=Object.entries(value);return <div className="grid gap-2 sm:grid-cols-2">{entries.slice(0,6).map(([key,item])=><div key={key} className="flex items-center justify-between gap-3"><span className="text-[10px] text-muted-foreground">{human(key)}</span><span className="text-[10px] font-black">{typeof item==='boolean'?(item?'Ativo':'Inativo'):String(item??'—')}</span></div>)}{entries.length>6&&<p className="text-[10px] text-muted-foreground">+{entries.length-6} parâmetros</p>}</div>}return <pre className="line-clamp-4 whitespace-pre-wrap text-[10px] text-muted-foreground">{JSON.stringify(value,null,2)}</pre>}
function Metric({icon:Icon,label,value,detail}:{icon:typeof Settings2;label:string;value:number;detail:string}){return <article className="rounded-2xl border border-white/[.07] bg-[#0b0b0b] p-5"><Icon className="h-4 w-4 text-primary"/><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold">{label}</p><p className="mt-1 text-[10px] text-muted-foreground">{detail}</p></article>}
