import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { ArrowLeft, CalendarDays, LockKeyhole, Shield, Swords, Trophy, Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createApplicationServices } from '@/lib/infrastructure/repositories/supabase/factory'
import { Button } from '@/components/ui/button'

export const dynamic = 'force-dynamic'

export default async function CompetitionDetailPage({ params }: { params: Promise<{ id:string }> }) {
  const { id } = await params
  const supabase = await createClient()
  const { data:{ user } } = await supabase.auth.getUser()
  if (!user || user.is_anonymous) redirect('/auth/login')
  const services = createApplicationServices(supabase)
  const detail = await services.reads.competitionDetail.load(user.id, id)
  if (!detail) notFound()

  return <div className="space-y-7">
    <Link href={`/tournaments?universe=${detail.universe.id}`} className="inline-flex items-center gap-2 text-sm text-muted-foreground transition hover:text-foreground"><ArrowLeft className="h-4 w-4" />Voltar às competições</Link>

    <section className="brand-watermark rounded-2xl border border-white/[0.07] bg-[#0b0b0b] px-5 py-6 sm:px-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-md border border-primary/15 bg-primary/[0.04] px-2 py-1 text-[9px] font-bold uppercase tracking-[0.13em] text-primary">{detail.competition.type}</span><span className="rounded-md border border-white/[0.07] px-2 py-1 text-[9px] font-bold uppercase tracking-[0.13em] text-muted-foreground">{detail.competition.status}</span></div><h1 className="mt-3 text-3xl font-black tracking-[-0.04em] sm:text-4xl">{detail.competition.name}</h1><p className="mt-3 text-sm text-muted-foreground">{detail.universe.name}{detail.season ? ` · ${detail.season.name}` : ' · sem época associada'}</p></div><Button asChild variant="outline"><Link href={`/play?universe=${detail.universe.id}`}><Swords className="mr-2 h-4 w-4" />Partidas do clube</Link></Button></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Participantes" value={detail.participants.length.toString()} detail={detail.viewerClub ? `Teu clube: ${detail.viewerClub.name}` : 'Sem clube neste universo'} /><Metric icon={CalendarDays} label="Rounds" value={detail.rounds.length.toString()} detail={`${detail.fixtures.length} partida(s) agendada(s/registada(s))`} /><Metric icon={Trophy} label="Prize pool" value={`${detail.competition.prizePool.toLocaleString('pt-PT')} S`} detail={`Entry fee: ${detail.competition.entryFee.toLocaleString('pt-PT')} S`} /><Metric icon={Shield} label="Inscrição" value={detail.registration?.state ?? 'SEM REGISTO'} detail="Ação bloqueada até existir settlement Silver atómico" /></section>

    <section className="rounded-2xl border border-primary/15 bg-primary/[0.025] p-5"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><div><p className="text-sm font-bold">Inscrição ainda não é uma ação pública</p><p className="mt-1 text-xs leading-5 text-muted-foreground">O RPC atual regista o clube mas não liquida `entry_fee`. Até o pagamento Silver e o registo serem uma única transação idempotente, esta página limita-se a mostrar o estado real.</p></div></div></section>

    {detail.standings.length > 0 && <section className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><SectionTitle kicker="Classificação" title="League standing" /><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-white/[0.07] text-left text-[10px] uppercase tracking-[0.13em] text-muted-foreground"><th className="pb-3">#</th><th className="pb-3">Clube</th><th className="pb-3 text-center">J</th><th className="pb-3 text-center">V</th><th className="pb-3 text-center">E</th><th className="pb-3 text-center">D</th><th className="pb-3 text-center">GM</th><th className="pb-3 text-center">GS</th><th className="pb-3 text-right">Pts</th></tr></thead><tbody>{detail.standings.map(({standing,club},index)=><tr key={club.id} className="border-b border-white/[0.05]"><td className="py-3 font-black">{standing.position ?? index+1}</td><td className="py-3 font-semibold">{club.name}</td><td className="py-3 text-center">{standing.played}</td><td className="py-3 text-center">{standing.won}</td><td className="py-3 text-center">{standing.drawn}</td><td className="py-3 text-center">{standing.lost}</td><td className="py-3 text-center">{standing.goalsFor}</td><td className="py-3 text-center">{standing.goalsAgainst}</td><td className="py-3 text-right font-black text-primary">{standing.points}</td></tr>)}</tbody></table></div></section>}

    <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
      <div className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><SectionTitle kicker="Estrutura" title="Rounds e divisões" /><div className="mt-5 space-y-3">{detail.rounds.length===0?<Empty text="Ainda não existem rounds."/>:detail.rounds.map(round=><div key={round.id} className="rounded-xl border border-white/[0.06] p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold">{round.roundNumber}. {round.name}</p><span className="text-[9px] font-bold uppercase tracking-[0.12em] text-muted-foreground">{round.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{round.startsAt?new Date(round.startsAt).toLocaleDateString('pt-PT'):'Sem início'} → {round.endsAt?new Date(round.endsAt).toLocaleDateString('pt-PT'):'sem fim'}</p></div>)}</div>{detail.divisions.length>0&&<div className="mt-5 border-t border-white/[0.06] pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-muted-foreground">Divisões</p><div className="mt-3 space-y-2">{detail.divisions.map(div=><div key={div.id} className="flex items-center justify-between gap-3 text-sm"><span>{div.level}. {div.name}</span><span className="text-xs text-muted-foreground">↑ {div.promotionSlots} · ↓ {div.relegationSlots}</span></div>)}</div></div>}</div>

      <div className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><SectionTitle kicker="Calendário" title="Fixtures" /><div className="mt-5 divide-y divide-white/[0.06] border-y border-white/[0.06]">{detail.fixtures.length===0?<Empty text="Ainda não existem partidas nesta competição."/>:detail.fixtures.map(fixture=><div key={fixture.match.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-sm font-bold">{fixture.homeClub.name} <span className="mx-2 text-white/20">vs</span> {fixture.awayClub.name}</p><p className="mt-1 text-xs text-muted-foreground">{fixture.roundName??(fixture.matchday?`Jornada ${fixture.matchday}`:'Sem round')} · {fixture.match.scheduledAt?new Date(fixture.match.scheduledAt).toLocaleString('pt-PT'):'Data por definir'}</p></div><div className="text-left sm:text-right"><p className="text-sm font-black">{fixture.match.homeScore!==null?`${fixture.match.homeScore} — ${fixture.match.awayScore}`:'—'}</p><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-muted-foreground">{fixture.match.state}</p></div></div>)}</div></div>
    </section>

    {detail.cupTies.length>0&&<section className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><SectionTitle kicker="Knockout" title="Cup ties" /><div className="mt-5 grid gap-3 md:grid-cols-2">{detail.cupTies.map(({tie,homeClub,awayClub,winnerClub})=><div key={tie.id} className="rounded-xl border border-white/[0.06] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-muted-foreground">Round {tie.roundNumber} · Tie {tie.tieNumber}</p><p className="mt-2 text-sm font-bold">{homeClub?.name??'TBD'} vs {awayClub?.name??'TBD'}</p><p className="mt-2 text-xs text-muted-foreground">{tie.state}{winnerClub?` · vencedor ${winnerClub.name}`:''}</p></div>)}</div></section>}

    <section className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5 sm:p-6"><SectionTitle kicker="Participantes" title="Clubes" /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{detail.participants.length===0?<Empty text="Ainda não existem participantes."/>:detail.participants.map(({participant,club})=><div key={participant.id} className="rounded-xl border border-white/[0.06] p-4"><p className="font-bold">{club.name}</p><p className="mt-1 text-xs text-muted-foreground">Elo {club.elo.toLocaleString('pt-PT')} · seed {participant.seed??'—'}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.12em] text-primary">{participant.status}</p></div>)}</div></section>
  </div>
}

function Metric({icon:Icon,label,value,detail}:{icon:typeof Trophy;label:string;value:string;detail:string}){return <article className="rounded-2xl border border-white/[0.07] bg-[#0b0b0b] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground"><Icon className="h-4 w-4 text-primary"/>{label}</div><p className="mt-3 text-xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>}
function SectionTitle({kicker,title}:{kicker:string;title:string}){return <div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">{kicker}</p><h2 className="mt-1 text-xl font-black">{title}</h2></div>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-muted-foreground">{text}</p>}
